### ISSUE TITLE
Focus On Open

### ISSUE THREAD

**Issue by loujaybee** [abircb/search-github#1]
It'd be neat if the plugin auto focused the input so it can be used immediately on open.

**Comment by loujaybee** [comment]
PR raised: https://github.com/abircb/search-github/pull/2

**Comment by abircb** [comment]
@loujaybee Great idea - although it wasn't implemented due to some (personal) aesthetic reasons before, I can understand why this feature would make the extension more usable and convenient for a user.

#### I have now merged your pull request and will notify you when the Chrome Webstore approves this new release. 

Thank you for your contribution!
